// app/inertia/pages/stats.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Head, Link } from '@inertiajs/vue3'
import NavBar from '../components/NavBar.vue'
import WordsStats from '../components/WordsStats.vue'
import type { WordsPoolWithDay } from '../types/wordsPool'
import { getCurrentDateFormatted } from '../utils/date'

defineProps<{
  wordsPool: WordsPoolWithDay | null
}>()

const todayUrl = computed(() => `/game/${getCurrentDateFormatted()}`)
</script>

<template>
  <Head title="Statistiques" />
  <div class="container mx-auto">
    <NavBar />
    <WordsStats
      v-if="wordsPool"
      :words-pool="wordsPool"
    />
    <div
      v-else
      class="text-center mt-10 text-gray-500"
    >
      Aucun jeu disponible pour aujourd'hui
    </div>
    <Link
      :href="todayUrl"
      class="block text-lg font-bold text-center mt-10 py-3 px-6 rounded border border-gray-100 bg-gray-50 dark:bg-gray-600 dark:border-gray-500 w-fit mx-auto mb-5"
    >
      Retourner au jeu
    </Link>
  </div>
</template>

// frontend/src/pages/Stats.tsx
import { NavBar } from '@/components/molecules';
import WordsStats from '@/components/organisms/WordsStats';
import { NavLink } from 'react-router-dom';
import { getCurrentDateFormatted } from '@/utils/date';

function Stats() {
  const day = getCurrentDateFormatted();

  return (
    <div className="container mx-auto">
      <NavBar />
      <WordsStats day={day} />
      <NavLink
        to="/"
        className="block text-lg font-bold text-center mt-10 py-3 px-6 rounded border border-gray-100 bg-gray-50 dark:bg-gray-600 dark:border-gray-500 w-fit mx-auto"
      >
        Retourner au jeu
      </NavLink>
    </div>
  );
}

export default Stats;
